# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0481a1cb761a1fbe70b84f6cdcd15edc3c9047488a6dc22ca81b51c03e182fec671a3f02d1435e59a9c9bcd151635bd65c40bff1a4ca8f11bc8305775d921c2

test:
  secret_key_base: c55a9c0f11e09b579d04024832bd092a2c1d5d1d831972c397a12cb68174ef787cc7742a1528562f82fdc830e526bc0c775c32d9dfcd98f4dcfef6bf759d7ce1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
